@userId = 1
@amount = 100
@outRefundNo = WD20250418202430c489e866

POST http://localhost:9805/userplat/wallet/withdrawal/apply?
    userId={{userId}}&
    amount={{amount}}&
    reason=reason


###
POST http://localhost:9805/userplat/wallet/withdrawal/callback
Content-Type: application/json

{
  "outRefundNo": "{{outRefundNo}}",
  "refundId":"mock_{{outRefundNo}}",
  "status": "e"
}
